source 'https://github.com/CocoaPods/Specs.git'

def pods

# Utilities
swift_version = "3.0"
pod 'PromiseKit', '~> 4.0'

# Extensionsb
pod 'EZSwiftExtensions'

# Core Data
pod 'CoreStore'

# Calendar
pod 'Koyomi'

# JSON
pod 'SwiftyJSON'

# Google places
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'GooglePlacePicker'

# Auto layout
pod 'SnapKit', '~> 3.2.0'

# Progress
pod 'SVProgressHUD'

# swift integration
use_frameworks!

# who cares about warnings
inhibit_all_warnings!

end

target 'Hotelzzz' do
    pods
end
